
import 'package:blue_model/blue_model.dart';
import 'package:flutter/material.dart';


class FormBuilderText extends FormBuilderTextField{
  FormBuilderText({super.key,
    required super.name,
    super.validator,
    super.decoration,
    super.onChanged,
    super.valueTransformer,
    super.enabled,
    super.onSaved,
    super.autovalidateMode = AutovalidateMode.disabled,
    super.onReset,
    super.focusNode,
    super.restorationId,
    super.initialValue,
    super.readOnly = false,
    super.maxLines = 1,
    super.obscureText = false,
    super.textCapitalization = TextCapitalization.none,
    super.scrollPadding = const EdgeInsets.all(20.0),
    super.enableInteractiveSelection = true,
    super.maxLengthEnforcement,
    super.textAlign = TextAlign.start,
    super.autofocus = false,
    super.autocorrect = true,
    super.cursorWidth = 2.0,
    super.cursorHeight,
    super.keyboardType,
    super.style,
    super.controller,
    super.textInputAction,
    super.strutStyle,
    super.textDirection,
    super.maxLength,
    super.onEditingComplete,
    super.onSubmitted,
    super.inputFormatters,
    super.cursorRadius,
    super.cursorColor,
    super.keyboardAppearance,
    super.buildCounter,
    super.expands = false,
    super.minLines,
    super.showCursor,
    super.onTap,
    super.onTapOutside,
    super.enableSuggestions = false,
    super.textAlignVertical,
    super.scrollController,
    super.scrollPhysics,
    super.smartDashesType,
    super.smartQuotesType,
    super.autofillHints,
    super.obscuringCharacter = '•',
    super.mouseCursor,
    super.magnifierConfiguration,
    super.contentInsertionConfiguration,
    super.spellCheckConfiguration,
  });
}