name: blue_model
description: "Flutter model factory library"
repository: 'https://github.com/ysfgrl/f_model_factory.git'
homepage: 'https://github.com/ysfgrl/f_model_factory.git'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.0.0
  mime: ^1.0.0
  file_picker: ^10.3.3
  json_annotation: ^4.9.0
  flutter_form_builder: ^10.0.0
  form_builder_validators: ^11.0.0
  form_builder_file_picker: ^5.0.0
  community_material_icon: ^5.9.55
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: